server:
  port: 8088
  domain: http://localhost

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_boilerplate
#    driverClassName: org.h2.Driver
    username: root
    password: roottoor
#    url: jdbc:h2:file:./testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


h2:
    console:
      enabled: true
      path: /h2
management:
  endpoint:
    metrics:
      enabled: false