server:
  port: 8088
  domain: http://localhost

spring:
  datasource:
    url: jdbc:h2:file:./testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2
management:
  endpoint:
    metrics:
      enabled: false