server:
  port: 8888
  domain: http://localhost

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  access-secret: 6xn3qdctOU2oGgTQHKXcn7JFnvbcVXxSf7fIBP5rfn0
  refresh-secret: 6xn3qdctOU2oGgTQHKXcn7JFnvbcVXxSf7fIBP5rfn0
  access-validity: 30000
  refresh-validity: 50000
  issuer: https://rasello.com

mail:
  host: smtp.gmail.com
  port: 587
  username: info.av91@gmail.com
  password: N3pal@312!
  debug: true
  smtp:
    auth: true
    starttls: true
  transport:
    protocol: smtp

springdoc:
  swagger-ui:
    path: /swagger-ui.html

camunda.bpm:
#  admin-user:
#    id: demo
#    password: demo
#    firstName: Demo
#    lastName: Demo
  filter:
    create: All Tasks
  authorization:
    enabled: true

keycloak:
  realm: camunda
  auth-server-url: http://124.41.241.106:8080/auth/
  resource: camunda-identity-service
  ssl-required: none
  credentials.secret : pdgDzBNzeYkJmxHfUC1KjU4v5BwQ9myb

plugin.identity.keycloak:
  keycloakIssuerUrl: http://124.41.241.106:8080/auth/realms/camunda
  keycloakAdminUrl: http://124.41.241.106:8080/auth/admin/realms/camunda
  clientId: camunda-identity-service
  clientSecret: pdgDzBNzeYkJmxHfUC1KjU4v5BwQ9myb
  useUsernameAsCamundaUserId: true
  disableSSLCertificateValidation: true