server:
  port: 8888
  domain: http://localhost

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  access-secret: 6xn3qdctOU2oGgTQHKXcn7JFnvbcVXxSf7fIBP5rfn0
  refresh-secret: 6xn3qdctOU2oGgTQHKXcn7JFnvbcVXxSf7fIBP5rfn0
  access-validity: 30000
  refresh-validity: 50000
  issuer: https://rasello.com

mail:
  host: smtp.gmail.com
  port: 587
  username: info.av91@gmail.com
  password: N3pal@312!
  debug: true
  smtp:
    auth: true
    starttls: true
  transport:
    protocol: smtp

springdoc:
  swagger-ui:
    path: /swagger-ui.html
#    disable-swagger-default-url: true
#  remove-broken-reference-definitions: false

camunda.bpm:
  job-execution:
    deployment-aware: true
  history-level: FULL
  authorization.enabled: true
  default-serialization-format: application/json
  filter.create: All Tasks

rest.security:
  enabled: true
  provider: keycloak
  required-audience: camunda-rest-api

keycloak:
  realm: camunda
  auth-server-url: http://124.41.241.106:8080/auth/
  resource: camunda-identity-service
  ssl-required: none
  credentials.secret : pdgDzBNzeYkJmxHfUC1KjU4v5BwQ9myb

plugin.identity.keycloak:
  keycloakIssuerUrl: http://124.41.241.106:8080/auth/realms/camunda
  keycloakAdminUrl: http://124.41.241.106:8080/auth/admin/realms/camunda
  clientId: camunda-identity-service
  clientSecret: pdgDzBNzeYkJmxHfUC1KjU4v5BwQ9myb
  useUsernameAsCamundaUserId: true
  disableSSLCertificateValidation: true
  administratorGroupName: camunda-admin

# Spring Boot Security OAuth2 SSO
spring.security:
  oauth2:
    client:
      registration:
        keycloak:
          provider: keycloak
          client-id: camunda-identity-service
          client-secret: pdgDzBNzeYkJmxHfUC1KjU4v5BwQ9myb
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope: openid, profile, email
      provider:
        keycloak:
          issuer-uri: http://124.41.241.106:8080/auth/realms/camunda
          authorization-uri: http://124.41.241.106:8080/auth/realms/camunda/protocol/openid-connect/auth
          user-info-uri: http://124.41.241.106:8080/auth/realms/camunda/protocol/openid-connect/userinfo
          token-uri: http://124.41.241.106:8080/auth/realms/camunda/protocol/openid-connect/token
          jwk-set-uri: http://124.41.241.106:8080/auth/realms/camunda/protocol/openid-connect/certs
          # set user-name-attribute one of:
          # - sub                -> default; using keycloak ID as camunda user ID
          # - email              -> useEmailAsCamundaUserId=true
          # - preferred_username -> useUsernameAsCamundaUserId=true
          user-name-attribute: preferred_username
